### ISSUE TITLE
Restore index command failing

### ISSUE THREAD

**Issue by K-7** [aptible/elasticsearch-logstash-s3-backup#12]
I was successful to archive an index to Amazon S3. But when tried to restore the same index back to elastic, the restore script throws an exception. ie 

{"error":{"root_cause":[{"type":"snapshot_restore_exception","reason":"[audit_snapshots:audit-2017.02.01] cannot restore index [audit-2017.02.01] because it's open"}],"type":"snapshot_restore_exception","reason":"[audit_snapshots:audit-2017.02.01] cannot restore index [audit-2017.02.01] because it's open"},"status":500}

I noticed that in the backup-all-indexes.sh we open the index and later delete it.
curl -sS -XPOST "${INDEX_URL}/_open"
curl -w "\n" -sS -XDELETE ${INDEX_URL}

Through the index was deleted, when I tried to check the available indices, the deleted index was still available though data was not present. 
Not able to understand what is happening. Kindly help me out.

**Comment by krallin** [comment]
As I mentioned to you on Slack; this is happening because you set `MAX_DAYS_TO_KEEP=0`, so you archived an index that was being written to and which therefore got promptly recreated after you archived it.

We'll be adding a guard in the script to disallow setting `MAX_DAYS_TO_KEEP` to values that are too low.
